# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-24 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180624_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='documents/codiecon/'),
        ),
    ]
